"""
TP4 — gRPC Metrics Streaming Server
=====================================
Protocol stack: gRPC → HTTP/2 → TCP → IP
Encryption    : None (insecure channel — easier to observe in Wireshark)

Objective
---------
Implement a gRPC server that streams simulated network metrics to a client.
The client connects once and receives 10 metric updates, one per second.

gRPC uses Protocol Buffers (protobuf) for message serialization and HTTP/2
as its transport layer. You will observe HTTP/2 DATA frames in Wireshark,
but their content will be binary (protobuf-encoded) — not plain text.

Instructions
------------
Complete the 4 TODO sections below.
Do NOT modify any code outside the TODO sections.
Run the server with:  python server.py
Then in a second terminal: python client.py
"""

import grpc
import time
import random
import datetime
from concurrent import futures

import metrics_pb2
import metrics_pb2_grpc

# ──────────────────────────────────────────────────────────────────
# CONFIGURATION — Complete TODO 1
# ──────────────────────────────────────────────────────────────────

# TODO 1: Choose a port number for the gRPC server.
#
#   Rules: must be an integer greater than 1024 (no root required).
#   The conventional gRPC development port is 50051.
#
PORT = ????

# Number of metric updates to stream per client connection.
STREAM_COUNT = 10


# ──────────────────────────────────────────────────────────────────
# gRPC SERVICE IMPLEMENTATION — Complete TODOs 2, 3, 4
# ──────────────────────────────────────────────────────────────────

class MetricsServicer(metrics_pb2_grpc.MetricsServiceServicer):
    """
    Implements the MetricsService RPC defined in metrics.proto.

    The base class (MetricsServiceServicer) is generated by grpc_tools.
    We override the StreamMetrics method to provide the actual logic.
    """

    def StreamMetrics(self, request, context):
        """
        Server-side streaming RPC.

        The client sends one MetricsRequest; the server yields multiple
        MetricUpdate messages over time.

        The 'yield' keyword makes this a Python generator — each yielded
        message is sent immediately to the client over the gRPC/HTTP2 stream.

        Complete TODOs 2 and 3 below.
        """
        print(f"  [gRPC] New client connected: client_id='{request.client_id}'")

        for i in range(STREAM_COUNT):

            # TODO 2: Build a MetricUpdate protobuf message with simulated values.
            #
            #   Use metrics_pb2.MetricUpdate(...) to create the message.
            #   Fill in all four fields:
            #
            #     timestamp   : current time as ISO string
            #                   → datetime.datetime.now().isoformat(timespec="seconds")
            #
            #     bandwidth_mb: random float between 10.0 and 100.0
            #                   → round(random.uniform(10.0, 100.0), 2)
            #
            #     latency_ms  : random float between 1.0 and 50.0
            #                   → round(random.uniform(1.0, 50.0), 2)
            #
            #     packet_loss : random integer between 0 and 5
            #                   → random.randint(0, 5)
            #
            update = metrics_pb2.MetricUpdate(
                timestamp    = ????,
                bandwidth_mb = ????,
                latency_ms   = ????,
                packet_loss  = ????,
            )

            # TODO 3: Send the update to the client.
            #
            #   In a server-side streaming RPC, each message is sent by
            #   using the 'yield' keyword — this function is a generator.
            #   The gRPC framework sends the yielded object immediately to
            #   the client over the open HTTP/2 stream.
            #
            #   Syntax:  yield <message>
            #
            ???? update

            print(f"  [update {i+1:>2}/{STREAM_COUNT}] "
                  f"bw={update.bandwidth_mb:.1f} MB/s  "
                  f"lat={update.latency_ms:.1f} ms  "
                  f"loss={update.packet_loss}%")

            time.sleep(1)

        print(f"  [gRPC] Stream complete for '{request.client_id}'\n")


# ──────────────────────────────────────────────────────────────────
# SERVER STARTUP — Complete TODO 4
# ──────────────────────────────────────────────────────────────────

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=4))

    # TODO 4: Register the service implementation with the gRPC server.
    #
    #   grpc_tools generated a helper function named:
    #       add_MetricsServiceServicer_to_server(servicer, server)
    #   It is available in the metrics_pb2_grpc module.
    #
    #   Call it with:
    #     - a new MetricsServicer() instance as the first argument
    #     - 'server' as the second argument
    #
    #   Complete the line below (replace ????):
    #
    metrics_pb2_grpc.????(MetricsServicer(), server)

    server.add_insecure_port(f"[::]:{PORT}")
    server.start()

    print(f"\n  gRPC Metrics server started")
    print(f"  Listening on: grpc://localhost:{PORT}  (insecure / no TLS)")
    print(f"  Wireshark filter: tcp.port == {PORT}")
    print(f"\n  In a second terminal, run:  python client.py")
    print(f"  The server will stream {STREAM_COUNT} metric updates, one per second.\n")

    server.wait_for_termination()


if __name__ == "__main__":
    serve()
