"""
TP2 — HTTP/2 File Transfer Server
======================================
Protocol stack: HTTP/2 → TLS 1.3 → TCP → IP
Encryption    : TLS 1.3 — content is encrypted, only handshake metadata visible

Objective
---------
Configure the TLS parameters that enable HTTP/2.
You will then observe the TLS handshake in Wireshark and confirm that:
  - Traffic is encrypted (unlike TP1)
  - Only one TCP connection is used for all requests (HTTP/2 multiplexing)
  - The ALPN extension negotiates the "h2" protocol during the TLS handshake

Instructions
------------
Complete the 5 TODO sections below.
Do NOT modify any code outside the TODO sections.

Run the server with:  python server.py
Then in a second terminal: python client.py
"""

import asyncio
import os

from quart import Quart, Response, request, send_file
from hypercorn.config import Config
from hypercorn.asyncio import serve as hypercorn_serve

# ──────────────────────────────────────────────────────────────────
# CONFIGURATION — Complete TODOs 1, 2, and 3
# ──────────────────────────────────────────────────────────────────

CERTS_DIR = os.path.join(os.path.dirname(__file__), "..", "certs")

# TODO 1: Set the filename of the TLS certificate generated by setup.sh.
#
#   setup.sh created two files inside the certs/ directory:
#     - server.crt   (the public certificate, sent to the browser)
#     - server.key   (the private key, kept secret on the server)
#
#   Replace ???? with the certificate filename (as a string, e.g. "server.crt").
#
CERT_FILE = os.path.join(CERTS_DIR, "????")


# TODO 2: Set the filename of the TLS private key.
#
#   Replace ???? with the key filename (as a string, e.g. "server.key").
#
KEY_FILE = os.path.join(CERTS_DIR, "????")


# TODO 3: Set the ALPN protocol identifier for HTTP/2.
#
#   ALPN (Application-Layer Protocol Negotiation) is a TLS extension that
#   lets the browser and server agree on which application protocol to use
#   BEFORE the TLS handshake is complete — without an extra round trip.
#
#   The browser sends a list of protocols it supports in the ClientHello.
#   The server picks one and confirms it in the ServerHello.
#   You will see this exchange in Wireshark.
#
#   The IANA-registered ALPN token for HTTP/2 is defined in RFC 7540 §11.
#   It is a short string. Search the RFC or look at the Wireshark capture
#   from a known HTTP/2 website.
#
#   Replace ???? with the correct ALPN token string.
#   (This value will be printed at startup — look for it in Wireshark.)
#
HTTP2_ALPN_TOKEN = "????"

PORT = 8443

# ──────────────────────────────────────────────────────────────────
# QUART APPLICATION (provided — do not modify)
# ──────────────────────────────────────────────────────────────────

DATA_PATH = os.path.join(os.path.dirname(__file__), "..", "assets", "data.txt")
app = Quart(__name__)


@app.route("/")
async def index():
    return await send_file(os.path.join(os.path.dirname(__file__), "index.html"))


@app.route("/data")
async def data():
    """Serve the data file with Range request support (same logic as TP1)."""
    file_size = os.path.getsize(DATA_PATH)
    range_header = request.headers.get("Range")

    if range_header:
        range_spec = range_header.replace("bytes=", "")
        parts = range_spec.split("-")
        start = int(parts[0])
        end   = int(parts[1]) if parts[1] else file_size - 1
        chunk_size = end - start + 1

        def generate():
            with open(DATA_PATH, "rb") as f:
                f.seek(start)
                yield f.read(chunk_size)

        headers = {
            "Content-Range":  f"bytes {start}-{end}/{file_size}",
            "Content-Length": str(chunk_size),
            "Accept-Ranges":  "bytes",
        }
        return Response(generate(), status=206, headers=headers, mimetype="text/plain")
    else:
        return await send_file(DATA_PATH, mimetype="text/plain")


# ──────────────────────────────────────────────────────────────────
# SERVER STARTUP — Complete TODOs 4 and 5
# ──────────────────────────────────────────────────────────────────

async def main():
    config = Config()

    # TODO 4: Set the listening address and port.
    #
    #   Format: "HOST:PORT"  (e.g. "0.0.0.0:8443" to listen on all interfaces)
    #   HTTPS uses port 443 by convention. Here we use 8443 (no root required).
    #
    #   Replace ???? with the port number.
    #
    config.bind = [f"0.0.0.0:????"]

    # TODO 5: Configure TLS by providing the certificate and key file paths.
    #
    #   Hypercorn uses these two files to set up TLS for HTTPS.
    #   Replace each ???? with the correct variable name defined above.
    #
    #   Note: Hypercorn automatically enables HTTP/2 when:
    #     (a) TLS is configured  AND  (b) the 'h2' Python package is installed
    #
    config.certfile = ????
    config.keyfile  = ????

    print(f"\n  HTTP/2 server started")
    print(f"  Listening on: https://localhost:{PORT}")
    print(f"  Wireshark filter: tls  (or: tcp.port == {PORT})")
    print(f"\n  Expected ALPN token in Wireshark ClientHello: {HTTP2_ALPN_TOKEN}")
    print(f"\n  In a second terminal, run:  python client.py")
    print("  Press Ctrl+C to stop.\n")

    await hypercorn_serve(app, config)


if __name__ == "__main__":
    asyncio.run(main())
