# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import metrics_pb2 as metrics__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in metrics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetricsServiceStub(object):
    """MetricsService exposes one RPC method with server-side streaming.
    The client sends a single MetricsRequest; the server streams back
    multiple MetricUpdate messages over the same HTTP/2 connection.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMetrics = channel.unary_stream(
                '/MetricsService/StreamMetrics',
                request_serializer=metrics__pb2.MetricsRequest.SerializeToString,
                response_deserializer=metrics__pb2.MetricUpdate.FromString,
                _registered_method=True)


class MetricsServiceServicer(object):
    """MetricsService exposes one RPC method with server-side streaming.
    The client sends a single MetricsRequest; the server streams back
    multiple MetricUpdate messages over the same HTTP/2 connection.
    """

    def StreamMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=metrics__pb2.MetricsRequest.FromString,
                    response_serializer=metrics__pb2.MetricUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MetricsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MetricsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetricsService(object):
    """MetricsService exposes one RPC method with server-side streaming.
    The client sends a single MetricsRequest; the server streams back
    multiple MetricUpdate messages over the same HTTP/2 connection.
    """

    @staticmethod
    def StreamMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MetricsService/StreamMetrics',
            metrics__pb2.MetricsRequest.SerializeToString,
            metrics__pb2.MetricUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
